name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Run Static Analysis
      run: ./build.ps1 Analyze

    # Run test portfolio here

    # Get build number here

    - name: Compile
      run: ./build.ps1 Compile -Configuration Release

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: ./build.ps1 Test
    
    # # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: MSIX Package
    #     path: ${{ env.Wap_Project_Directory }}\AppPackages
